# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-30 13:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seeker', '0002_auto_20150507_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResultsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('querystring', models.TextField(blank=True)),
                ('displayed_columns', models.TextField(blank=True)),
                ('url', models.CharField(db_index=True, max_length=200)),
                ('result_count', models.BigIntegerField()),
                ('date_searched', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_results_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_searched', 'user'),
            },
        ),
    ]
